export const ENV = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL ?? "",
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL ?? "",
  NEXT_PUBLIC_FRONTEND_USE_INTERNAL_API:
    process.env.NEXT_PUBLIC_FRONTEND_USE_INTERNAL_API ?? "",
  NEXT_PUBLIC_VOICE_GATEWAY_URL: process.env.NEXT_PUBLIC_VOICE_GATEWAY_URL ?? "",
  NEXT_PUBLIC_CONVERSATION_ENGINE_URL: process.env.NEXT_PUBLIC_CONVERSATION_ENGINE_URL ?? "",
  NEXT_PUBLIC_DEMO_MODE: process.env.NEXT_PUBLIC_DEMO_MODE ?? "",
  NEXT_PUBLIC_UPLOAD_ALLOWED: process.env.NEXT_PUBLIC_UPLOAD_ALLOWED ?? "",
  NEXT_PUBLIC_UPLOAD_MAX_MB: process.env.NEXT_PUBLIC_UPLOAD_MAX_MB ?? "",
  NEXT_PUBLIC_PAGE_SIZE: process.env.NEXT_PUBLIC_PAGE_SIZE ?? "",
  NEXT_PUBLIC_SSE_TIMEOUT_MS: process.env.NEXT_PUBLIC_SSE_TIMEOUT_MS ?? "",
  NEXT_PUBLIC_POLL_INTERVAL_MS: process.env.NEXT_PUBLIC_POLL_INTERVAL_MS ?? "",
  NEXT_PUBLIC_POLL_MAX_MINUTES: process.env.NEXT_PUBLIC_POLL_MAX_MINUTES ?? "",
} as const

type EnvKey = keyof typeof ENV

export function getEnv(key: EnvKey) {
  return ENV[key]
}

if (typeof window !== "undefined") {
  if (!ENV.NEXT_PUBLIC_API_URL) {
    console.warn("Falta NEXT_PUBLIC_API_URL")
  }
}
