version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: salomon
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: salomon
    command: ["postgres","-c","shared_buffers=256MB","-c","max_connections=200"]
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U salomon -d salomon"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      DB_USER: salomon
      DB_PASSWORD: ${PG_PASSWORD}
      DB_HOST: postgres
      DB_NAME: salomon
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 400
      DEFAULT_POOL_SIZE: 40
    depends_on: [postgres]
    ports: ["6432:6432"]

volumes:
  pg_data:
