# Configuración de Prometheus para SalomónAI
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Reglas de alertas
rule_files:
  - "alert_rules.yml"

# Configuración de Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuración de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Core API monitoring
  - job_name: 'core-api'
    static_configs:
      - targets: ['core-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Frontend monitoring (si tiene métricas)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Node Exporter para métricas del sistema
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor para métricas de contenedores
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Nginx metrics (si nginx-prometheus-exporter está configurado)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # PostgreSQL metrics (si está configurado)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']